---
layout: cv
title: William Delgado's CV
---
# William Delgado
Web Developer, Student, Teaching Assistant.

<div id="webaddress">
<a href="del24030@byui.edu">del24030@byui.edu</a>
| <a href="https://www.linkedin.com/in/william-delgado-a61504352/">My linkendin page</a>
</div>


## Currently

Pursuing a Bachelor's degree in Computer Science at Brigham Young University - Idaho.

### Specialized in

Web development, interactive and responsive design, Python, JavaScript, HTML, CSS, problem-solving, and teamwork.

### Research interests

Software development, user experience design, web accessibility, and collaborative coding.

## Education

`2012 - 2020`
__School Las Ameicas, Bucaramanga, Colombia__

`September 2024-Present`
__Brigham Young University - Idaho, Rexburg, Idaho.__

## Awards

None

## Publications

None

### Journals

None

### Patents

None

## Occupation

`January 2025`
__Teaching Assistant__, Brigham Young University - Idaho

`May 2024 - August 2024`
__Customer Service Agent__, Teleperformance



<!-- ### Footer

Last updated: Apr 2025 -->